services:
  - type: web
    name: trugoodbeautiful-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CONTENTFUL_SPACE_ID
        sync: false
      - key: CONTENTFUL_ACCESS_TOKEN
        sync: false